/**
 * @file types_data.c
 * @brief Global data arrays and lookup tables
 * 
 * Defines and initializes global constant arrays used throughout the engine:
 * - Piece properties (color, type, value)
 * - Character representations for pieces, files, ranks
 * - Evaluation masks for pawn structure
 * - Board geometry (files and ranks for each square)
 * - Piece movement properties (sliding, knight, king)
 * 
 * These arrays provide O(1) lookup for piece properties and board
 * geometry, improving performance throughout the engine.
 * 
 * @author Gambit Chess Team
 * @date February 2026
 */

#include "types_definitions.h"

char PceChar[] = ".PNBRQKpnbrqk";
char SideChar[] = "wb-";
char RankChar[] = "12345678";
char FileChar[] = "abcdefgh";

int PieceBig[13] = { BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_TRUE, BOOL_TYPE_TRUE, BOOL_TYPE_TRUE, BOOL_TYPE_TRUE, BOOL_TYPE_TRUE, BOOL_TYPE_FALSE, BOOL_TYPE_TRUE, BOOL_TYPE_TRUE, BOOL_TYPE_TRUE, BOOL_TYPE_TRUE, BOOL_TYPE_TRUE };
int PieceMaj[13] = { BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_TRUE, BOOL_TYPE_TRUE, BOOL_TYPE_TRUE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_TRUE, BOOL_TYPE_TRUE, BOOL_TYPE_TRUE };
int PieceMin[13] = { BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_TRUE, BOOL_TYPE_TRUE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_TRUE, BOOL_TYPE_TRUE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE };
int g_pieceVal[13]= { 0, 100, 325, 325, 550, 1000, 50000, 100, 325, 325, 550, 1000, 50000  };
int g_pieceCol[13] = { COLOR_TYPE_BOTH, COLOR_TYPE_WHITE, COLOR_TYPE_WHITE, COLOR_TYPE_WHITE, COLOR_TYPE_WHITE, COLOR_TYPE_WHITE, COLOR_TYPE_WHITE,
	COLOR_TYPE_BLACK, COLOR_TYPE_BLACK, COLOR_TYPE_BLACK, COLOR_TYPE_BLACK, COLOR_TYPE_BLACK, COLOR_TYPE_BLACK };
	
int g_piecePawn[13] = { BOOL_TYPE_FALSE, BOOL_TYPE_TRUE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_TRUE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE };	
int g_pieceKnight[13] = { BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_TRUE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_TRUE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE };
int g_pieceKing[13] = { BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_TRUE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_TRUE };
int g_pieceRookQueen[13] = { BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_TRUE, BOOL_TYPE_TRUE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_TRUE, BOOL_TYPE_TRUE, BOOL_TYPE_FALSE };
int g_pieceBishopQueen[13] = { BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_TRUE, BOOL_TYPE_FALSE, BOOL_TYPE_TRUE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_TRUE, BOOL_TYPE_FALSE, BOOL_TYPE_TRUE, BOOL_TYPE_FALSE };
int g_pieceSlides[13] = { BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_TRUE, BOOL_TYPE_TRUE, BOOL_TYPE_TRUE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_FALSE, BOOL_TYPE_TRUE, BOOL_TYPE_TRUE, BOOL_TYPE_TRUE, BOOL_TYPE_FALSE };

int Mirror64[64] = {
56	,	57	,	58	,	59	,	60	,	61	,	62	,	63	,
48	,	49	,	50	,	51	,	52	,	53	,	54	,	55	,
40	,	41	,	42	,	43	,	44	,	45	,	46	,	47	,
32	,	33	,	34	,	35	,	36	,	37	,	38	,	39	,
24	,	25	,	26	,	27	,	28	,	29	,	30	,	31	,
16	,	17	,	18	,	19	,	20	,	21	,	22	,	23	,
8	,	9	,	10	,	11	,	12	,	13	,	14	,	15	,
0	,	1	,	2	,	3	,	4	,	5	,	6	,	7
};
	